# Generated by Django 5.2.8 on 2025-11-29 15:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relecloud', '0006_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='image',
            field=models.ImageField(blank=True, help_text='Imagen del destino (formatos permitidos: JPG, JPEG, PNG, WEBP, máximo 5MB)', null=True, upload_to='destinations/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
    ]
