# Generated by GitHub Copilot on 2025-11-29 15:45

from django.db import migrations


def assign_images(apps, schema_editor):
    """
    Asigna las imágenes predefinidas a los destinos existentes.
    Solo asigna si el destino no tiene imagen ya asignada.
    """
    Destination = apps.get_model('relecloud', 'Destination')
    
    # Mapeo de nombres de destino a rutas de imagen
    image_mapping = {
        'Quevedo y Linton': 'destinations/3a084f45fd604d389661f085f7422e60.jpg',
        'luna': 'destinations/b1ab583ffe7f48d6ab0aad85849c523d.jpg',
        'Mars': 'destinations/4c66c507ded8411189cbb9d8152423bb.jpg',
        'Hoth': 'destinations/8c3d438b723e4f2fa779dded0d9f1450.jpg',
        'GonyiWorld': 'destinations/4b22298a5b0d45be88a21a7f3612eab9.jpg',
        'AlibaBaT': 'destinations/b2f9cc0bc9e84ec28d7cf2d0a59c698b.jpg',
        'LarenDOT': 'destinations/4f709e5a1f3548619fe2be4249f2fc7d.jpg',
        'TebiWorldy': 'destinations/1fcbaabd1378440f833ee1fc8e9b4656.jpg',
        'Tralaleritos': 'destinations/dc2d9475786a466f96b7b7ad270e6cc9.jpg',
        'Mustafar': 'destinations/52debcc1cd9141e5bc25c559b56cb689.jpg',
        'Bespin': 'destinations/ed85887b27fd419aa271d4056ff9c442.jpg',
        'Aelix2': 'destinations/6a0cc257c7a540c29e5fa7bde771b52b.jpg',
        'Mario atleti': 'destinations/e1d29d7153d9417185c532d2eb76b663.jpg',
    }
    
    # Asignar imágenes solo si el destino no tiene una ya
    for name, image_path in image_mapping.items():
        try:
            dest = Destination.objects.get(name=name)
            if not dest.image:
                dest.image = image_path
                dest.save(update_fields=['image'])
                print(f"✅ Imagen asignada a: {name}")
            else:
                print(f"⏭️  '{name}' ya tiene imagen, omitiendo...")
        except Destination.DoesNotExist:
            print(f"⚠️  Destino '{name}' no encontrado, omitiendo...")


def reverse_assign_images(apps, schema_editor):
    """
    Revierte la asignación de imágenes (opcional).
    En caso de rollback, limpia las imágenes asignadas.
    """
    Destination = apps.get_model('relecloud', 'Destination')
    
    image_paths = [
        'destinations/3a084f45fd604d389661f085f7422e60.jpg',
        'destinations/b1ab583ffe7f48d6ab0aad85849c523d.jpg',
        'destinations/4c66c507ded8411189cbb9d8152423bb.jpg',
        'destinations/8c3d438b723e4f2fa779dded0d9f1450.jpg',
        'destinations/4b22298a5b0d45be88a21a7f3612eab9.jpg',
        'destinations/b2f9cc0bc9e84ec28d7cf2d0a59c698b.jpg',
        'destinations/4f709e5a1f3548619fe2be4249f2fc7d.jpg',
        'destinations/1fcbaabd1378440f833ee1fc8e9b4656.jpg',
        'destinations/dc2d9475786a466f96b7b7ad270e6cc9.jpg',
        'destinations/52debcc1cd9141e5bc25c559b56cb689.jpg',
        'destinations/ed85887b27fd419aa271d4056ff9c442.jpg',
        'destinations/6a0cc257c7a540c29e5fa7bde771b52b.jpg',
        'destinations/e1d29d7153d9417185c532d2eb76b663.jpg',
    ]
    
    Destination.objects.filter(image__in=image_paths).update(image='')


class Migration(migrations.Migration):

    dependencies = [
        ('relecloud', '0007_destination_image'),
    ]

    operations = [
        migrations.RunPython(assign_images, reverse_code=reverse_assign_images),
    ]
