# Generated by Django 5.2.6 on 2025-12-02 11:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relecloud', '0007_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destination',
            options={'verbose_name': 'Destino', 'verbose_name_plural': 'Destinos'},
        ),
        migrations.AlterModelOptions(
            name='inforequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Solicitud de información', 'verbose_name_plural': 'Solicitudes de información'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at'], 'verbose_name': 'Review', 'verbose_name_plural': 'Reviews'},
        ),
        migrations.AddField(
            model_name='inforequest',
            name='approved',
            field=models.BooleanField(default=False, help_text='Indica si la compra fue confirmada', verbose_name='Aprobado'),
        ),
        migrations.AddField(
            model_name='inforequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de solicitud'),
        ),
        migrations.AddField(
            model_name='inforequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='info_requests', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='description',
            field=models.TextField(max_length=2000, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='slug',
            field=models.SlugField(verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='inforequest',
            name='cruise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='relecloud.cruise', verbose_name='Crucero'),
        ),
        migrations.AlterField(
            model_name='inforequest',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='inforequest',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='inforequest',
            name='notes',
            field=models.TextField(max_length=2000, verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(blank=True, default='', help_text='Comentario opcional (máximo 1000 caracteres)', max_length=1000, verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='review',
            name='cruise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='relecloud.cruise', verbose_name='Crucero'),
        ),
        migrations.AlterField(
            model_name='review',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='relecloud.destination', verbose_name='Destino'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(help_text='Puntuación de 1 a 5 estrellas', validators=[django.core.validators.MinValueValidator(1, message='La puntuación mínima es 1 estrella.'), django.core.validators.MaxValueValidator(5, message='La puntuación máxima es 5 estrellas.')], verbose_name='Puntuación'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
