# Generated by Django 5.2.6 on 2025-12-02 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relecloud', '0008_alter_destination_options_alter_inforequest_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inforequest',
            name='approved',
            field=models.BooleanField(default=True, help_text='Indica si la compra fue confirmada', verbose_name='Aprobado'),
        ),
    ]
