# Generated by Django 5.2.8 on 2025-12-02 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relecloud', '0008_assign_destination_images'),
        ('relecloud', '0009_alter_inforequest_approved'),
    ]

    operations = [
    ]
