# Generated by Django 5.2.8 on 2025-12-02 13:07

import django.core.validators
import relecloud.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relecloud', '0010_merge_20251202_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='image',
            field=models.ImageField(blank=True, help_text='Imagen del destino (formatos permitidos: JPG, JPEG, PNG, WEBP, máximo 5MB)', null=True, upload_to=relecloud.models.Destination.destination_image_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
    ]
